version: "3.9"
services:
  db:
    image: "postgres:16.4"
    restart: always
    healthcheck:
      test: "exit 0"
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  adminer:
    image: adminer
    restart: always
    ports:
      - ${ADMINER_PORT}:8080
